owner: GraditiPro
repo: standshare-status

sites:
  - name: Web App
    url: https://demo.standshare.app
  - name: API
    url: https://api.standshare.app/health
  - name: Admin Portal
    url: https://admin.standshare.app
  - name: Admin API
    url: https://admin-api.standshare.app/health
  - name: Docs
    url: https://docs.standshare.app
  - name: Marketing
    url: https://www.standshare.app

status-website:
  cname: status.standshare.app
  logoUrl: https://www.standshare.app/logo.png
  name: StandShare Status
  introTitle: "**StandShare** service status and uptime monitor."
  introMessage: Real-time status for all StandShare production services. Powered by [Upptime](https://github.com/upptime/upptime).
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
